/* MistCore 
ArashWoWer  UPDATE 
ArashWoWer@yahoo.com
*/ 

REPLACE INTO `playercreateinfo_spell` (`race`, `class`, `Spell`, `Note`) VALUES (24, 1, 131701, 'Racials of pandarens');
REPLACE INTO `playercreateinfo_spell` (`race`, `class`, `Spell`, `Note`) VALUES (24, 1, 107072, 'Racials of pandarens');
REPLACE INTO `playercreateinfo_spell` (`race`, `class`, `Spell`, `Note`) VALUES (24, 1, 107073, 'Racials of pandarens');
REPLACE INTO `playercreateinfo_spell` (`race`, `class`, `Spell`, `Note`) VALUES (24, 1, 107074, 'Racials of pandarens');
REPLACE INTO `playercreateinfo_spell` (`race`, `class`, `Spell`, `Note`) VALUES (24, 1, 107076, 'Racials of pandarens');
REPLACE INTO `playercreateinfo_spell` (`race`, `class`, `Spell`, `Note`) VALUES (24, 1, 107079, 'Racials of pandarens');
REPLACE INTO `playercreateinfo_spell` (`race`, `class`, `Spell`, `Note`) VALUES (24, 3, 131701, 'Racials of pandarens');
REPLACE INTO `playercreateinfo_spell` (`race`, `class`, `Spell`, `Note`) VALUES (24, 3, 107072, 'Racials of pandarens');
REPLACE INTO `playercreateinfo_spell` (`race`, `class`, `Spell`, `Note`) VALUES (24, 3, 107073, 'Racials of pandarens');
REPLACE INTO `playercreateinfo_spell` (`race`, `class`, `Spell`, `Note`) VALUES (24, 3, 107074, 'Racials of pandarens');
REPLACE INTO `playercreateinfo_spell` (`race`, `class`, `Spell`, `Note`) VALUES (24, 3, 107076, 'Racials of pandarens');
REPLACE INTO `playercreateinfo_spell` (`race`, `class`, `Spell`, `Note`) VALUES (24, 3, 107079, 'Racials of pandarens');
REPLACE INTO `playercreateinfo_spell` (`race`, `class`, `Spell`, `Note`) VALUES (24, 4, 131701, 'Racials of pandarens');
REPLACE INTO `playercreateinfo_spell` (`race`, `class`, `Spell`, `Note`) VALUES (24, 4, 107072, 'Racials of pandarens');
REPLACE INTO `playercreateinfo_spell` (`race`, `class`, `Spell`, `Note`) VALUES (24, 4, 107073, 'Racials of pandarens');
REPLACE INTO `playercreateinfo_spell` (`race`, `class`, `Spell`, `Note`) VALUES (24, 4, 107074, 'Racials of pandarens');
REPLACE INTO `playercreateinfo_spell` (`race`, `class`, `Spell`, `Note`) VALUES (24, 4, 107076, 'Racials of pandarens');
REPLACE INTO `playercreateinfo_spell` (`race`, `class`, `Spell`, `Note`) VALUES (24, 4, 107079, 'Racials of pandarens');
REPLACE INTO `playercreateinfo_spell` (`race`, `class`, `Spell`, `Note`) VALUES (24, 5, 131701, 'Racials of pandarens');
REPLACE INTO `playercreateinfo_spell` (`race`, `class`, `Spell`, `Note`) VALUES (24, 5, 107072, 'Racials of pandarens');
REPLACE INTO `playercreateinfo_spell` (`race`, `class`, `Spell`, `Note`) VALUES (24, 5, 107073, 'Racials of pandarens');
REPLACE INTO `playercreateinfo_spell` (`race`, `class`, `Spell`, `Note`) VALUES (24, 5, 107074, 'Racials of pandarens');
REPLACE INTO `playercreateinfo_spell` (`race`, `class`, `Spell`, `Note`) VALUES (24, 5, 107076, 'Racials of pandarens');
REPLACE INTO `playercreateinfo_spell` (`race`, `class`, `Spell`, `Note`) VALUES (24, 5, 107079, 'Racials of pandarens');
REPLACE INTO `playercreateinfo_spell` (`race`, `class`, `Spell`, `Note`) VALUES (24, 7, 131701, 'Racials of pandarens');
REPLACE INTO `playercreateinfo_spell` (`race`, `class`, `Spell`, `Note`) VALUES (24, 7, 107072, 'Racials of pandarens');
REPLACE INTO `playercreateinfo_spell` (`race`, `class`, `Spell`, `Note`) VALUES (24, 7, 107073, 'Racials of pandarens');
REPLACE INTO `playercreateinfo_spell` (`race`, `class`, `Spell`, `Note`) VALUES (24, 7, 107074, 'Racials of pandarens');
REPLACE INTO `playercreateinfo_spell` (`race`, `class`, `Spell`, `Note`) VALUES (24, 7, 107076, 'Racials of pandarens');
REPLACE INTO `playercreateinfo_spell` (`race`, `class`, `Spell`, `Note`) VALUES (24, 7, 107079, 'Racials of pandarens');
REPLACE INTO `playercreateinfo_spell` (`race`, `class`, `Spell`, `Note`) VALUES (24, 8, 131701, 'Racials of pandarens');
REPLACE INTO `playercreateinfo_spell` (`race`, `class`, `Spell`, `Note`) VALUES (24, 8, 107072, 'Racials of pandarens');
REPLACE INTO `playercreateinfo_spell` (`race`, `class`, `Spell`, `Note`) VALUES (24, 8, 107073, 'Racials of pandarens');
REPLACE INTO `playercreateinfo_spell` (`race`, `class`, `Spell`, `Note`) VALUES (24, 8, 107074, 'Racials of pandarens');
REPLACE INTO `playercreateinfo_spell` (`race`, `class`, `Spell`, `Note`) VALUES (24, 8, 107076, 'Racials of pandarens');
REPLACE INTO `playercreateinfo_spell` (`race`, `class`, `Spell`, `Note`) VALUES (24, 8, 107079, 'Racials of pandarens');
REPLACE INTO `playercreateinfo_spell` (`race`, `class`, `Spell`, `Note`) VALUES (24, 10, 131701, 'Racials of pandarens');
REPLACE INTO `playercreateinfo_spell` (`race`, `class`, `Spell`, `Note`) VALUES (24, 10, 107072, 'Racials of pandarens');
REPLACE INTO `playercreateinfo_spell` (`race`, `class`, `Spell`, `Note`) VALUES (24, 10, 107073, 'Racials of pandarens');
REPLACE INTO `playercreateinfo_spell` (`race`, `class`, `Spell`, `Note`) VALUES (24, 10, 107074, 'Racials of pandarens');
REPLACE INTO `playercreateinfo_spell` (`race`, `class`, `Spell`, `Note`) VALUES (24, 10, 107076, 'Racials of pandarens');
REPLACE INTO `playercreateinfo_spell` (`race`, `class`, `Spell`, `Note`) VALUES (24, 10, 107079, 'Racials of pandarens');
REPLACE INTO `playercreateinfo_spell` (`race`, `class`, `Spell`, `Note`) VALUES (24, 1, 108127, 'Language of Pandaren Neutral');
REPLACE INTO `playercreateinfo_spell` (`race`, `class`, `Spell`, `Note`) VALUES (24, 3, 108127, 'Language of Pandaren Neutral');
REPLACE INTO `playercreateinfo_spell` (`race`, `class`, `Spell`, `Note`) VALUES (24, 4, 108127, 'Language of Pandaren Neutral');
REPLACE INTO `playercreateinfo_spell` (`race`, `class`, `Spell`, `Note`) VALUES (24, 5, 108127, 'Language of Pandaren Neutral');
REPLACE INTO `playercreateinfo_spell` (`race`, `class`, `Spell`, `Note`) VALUES (24, 7, 108127, 'Language of Pandaren Neutral');
REPLACE INTO `playercreateinfo_spell` (`race`, `class`, `Spell`, `Note`) VALUES (24, 8, 108127, 'Language of Pandaren Neutral');
REPLACE INTO `playercreateinfo_spell` (`race`, `class`, `Spell`, `Note`) VALUES (24, 10, 108127, 'Language of Pandaren Neutral');
REPLACE INTO `playercreateinfo_spell` (`race`, `class`, `Spell`, `Note`) VALUES (25, 1, 107072, 'Racials of pandarens');
REPLACE INTO `playercreateinfo_spell` (`race`, `class`, `Spell`, `Note`) VALUES (25, 1, 107073, 'Racials of pandarens');
REPLACE INTO `playercreateinfo_spell` (`race`, `class`, `Spell`, `Note`) VALUES (25, 1, 107074, 'Racials of pandarens');
REPLACE INTO `playercreateinfo_spell` (`race`, `class`, `Spell`, `Note`) VALUES (25, 1, 107076, 'Racials of pandarens');
REPLACE INTO `playercreateinfo_spell` (`race`, `class`, `Spell`, `Note`) VALUES (25, 1, 107079, 'Racials of pandarens');
REPLACE INTO `playercreateinfo_spell` (`race`, `class`, `Spell`, `Note`) VALUES (25, 1, 108127, 'Language of Pandaren Neutral');
REPLACE INTO `playercreateinfo_spell` (`race`, `class`, `Spell`, `Note`) VALUES (25, 1, 131701, 'Racials of pandarens');
REPLACE INTO `playercreateinfo_spell` (`race`, `class`, `Spell`, `Note`) VALUES (25, 3, 107072, 'Racials of pandarens');
REPLACE INTO `playercreateinfo_spell` (`race`, `class`, `Spell`, `Note`) VALUES (25, 3, 107073, 'Racials of pandarens');
REPLACE INTO `playercreateinfo_spell` (`race`, `class`, `Spell`, `Note`) VALUES (25, 3, 107074, 'Racials of pandarens');
REPLACE INTO `playercreateinfo_spell` (`race`, `class`, `Spell`, `Note`) VALUES (25, 3, 107076, 'Racials of pandarens');
REPLACE INTO `playercreateinfo_spell` (`race`, `class`, `Spell`, `Note`) VALUES (25, 3, 107079, 'Racials of pandarens');
REPLACE INTO `playercreateinfo_spell` (`race`, `class`, `Spell`, `Note`) VALUES (25, 3, 108127, 'Language of Pandaren Neutral');
REPLACE INTO `playercreateinfo_spell` (`race`, `class`, `Spell`, `Note`) VALUES (25, 3, 131701, 'Racials of pandarens');
REPLACE INTO `playercreateinfo_spell` (`race`, `class`, `Spell`, `Note`) VALUES (25, 4, 107072, 'Racials of pandarens');
REPLACE INTO `playercreateinfo_spell` (`race`, `class`, `Spell`, `Note`) VALUES (25, 4, 107073, 'Racials of pandarens');
REPLACE INTO `playercreateinfo_spell` (`race`, `class`, `Spell`, `Note`) VALUES (25, 4, 107074, 'Racials of pandarens');
REPLACE INTO `playercreateinfo_spell` (`race`, `class`, `Spell`, `Note`) VALUES (25, 4, 107076, 'Racials of pandarens');
REPLACE INTO `playercreateinfo_spell` (`race`, `class`, `Spell`, `Note`) VALUES (25, 4, 107079, 'Racials of pandarens');
REPLACE INTO `playercreateinfo_spell` (`race`, `class`, `Spell`, `Note`) VALUES (25, 4, 108127, 'Language of Pandaren Neutral');
REPLACE INTO `playercreateinfo_spell` (`race`, `class`, `Spell`, `Note`) VALUES (25, 4, 131701, 'Racials of pandarens');
REPLACE INTO `playercreateinfo_spell` (`race`, `class`, `Spell`, `Note`) VALUES (25, 5, 107072, 'Racials of pandarens');
REPLACE INTO `playercreateinfo_spell` (`race`, `class`, `Spell`, `Note`) VALUES (25, 5, 107073, 'Racials of pandarens');
REPLACE INTO `playercreateinfo_spell` (`race`, `class`, `Spell`, `Note`) VALUES (25, 5, 107074, 'Racials of pandarens');
REPLACE INTO `playercreateinfo_spell` (`race`, `class`, `Spell`, `Note`) VALUES (25, 5, 107076, 'Racials of pandarens');
REPLACE INTO `playercreateinfo_spell` (`race`, `class`, `Spell`, `Note`) VALUES (25, 5, 107079, 'Racials of pandarens');
REPLACE INTO `playercreateinfo_spell` (`race`, `class`, `Spell`, `Note`) VALUES (25, 5, 108127, 'Language of Pandaren Neutral');
REPLACE INTO `playercreateinfo_spell` (`race`, `class`, `Spell`, `Note`) VALUES (25, 5, 131701, 'Racials of pandarens');
REPLACE INTO `playercreateinfo_spell` (`race`, `class`, `Spell`, `Note`) VALUES (25, 7, 107072, 'Racials of pandarens');
REPLACE INTO `playercreateinfo_spell` (`race`, `class`, `Spell`, `Note`) VALUES (25, 7, 107073, 'Racials of pandarens');
REPLACE INTO `playercreateinfo_spell` (`race`, `class`, `Spell`, `Note`) VALUES (25, 7, 107074, 'Racials of pandarens');
REPLACE INTO `playercreateinfo_spell` (`race`, `class`, `Spell`, `Note`) VALUES (25, 7, 107076, 'Racials of pandarens');
REPLACE INTO `playercreateinfo_spell` (`race`, `class`, `Spell`, `Note`) VALUES (25, 7, 107079, 'Racials of pandarens');
REPLACE INTO `playercreateinfo_spell` (`race`, `class`, `Spell`, `Note`) VALUES (25, 7, 108127, 'Language of Pandaren Neutral');
REPLACE INTO `playercreateinfo_spell` (`race`, `class`, `Spell`, `Note`) VALUES (25, 7, 131701, 'Racials of pandarens');
REPLACE INTO `playercreateinfo_spell` (`race`, `class`, `Spell`, `Note`) VALUES (25, 8, 107072, 'Racials of pandarens');
REPLACE INTO `playercreateinfo_spell` (`race`, `class`, `Spell`, `Note`) VALUES (25, 8, 107073, 'Racials of pandarens');
REPLACE INTO `playercreateinfo_spell` (`race`, `class`, `Spell`, `Note`) VALUES (25, 8, 107074, 'Racials of pandarens');
REPLACE INTO `playercreateinfo_spell` (`race`, `class`, `Spell`, `Note`) VALUES (25, 8, 107076, 'Racials of pandarens');
REPLACE INTO `playercreateinfo_spell` (`race`, `class`, `Spell`, `Note`) VALUES (25, 8, 107079, 'Racials of pandarens');
REPLACE INTO `playercreateinfo_spell` (`race`, `class`, `Spell`, `Note`) VALUES (25, 8, 108127, 'Language of Pandaren Neutral');
REPLACE INTO `playercreateinfo_spell` (`race`, `class`, `Spell`, `Note`) VALUES (25, 8, 131701, 'Racials of pandarens');
REPLACE INTO `playercreateinfo_spell` (`race`, `class`, `Spell`, `Note`) VALUES (25, 10, 107072, 'Racials of pandarens');
REPLACE INTO `playercreateinfo_spell` (`race`, `class`, `Spell`, `Note`) VALUES (25, 10, 107073, 'Racials of pandarens');
REPLACE INTO `playercreateinfo_spell` (`race`, `class`, `Spell`, `Note`) VALUES (25, 10, 107074, 'Racials of pandarens');
REPLACE INTO `playercreateinfo_spell` (`race`, `class`, `Spell`, `Note`) VALUES (25, 10, 107076, 'Racials of pandarens');
REPLACE INTO `playercreateinfo_spell` (`race`, `class`, `Spell`, `Note`) VALUES (25, 10, 107079, 'Racials of pandarens');
REPLACE INTO `playercreateinfo_spell` (`race`, `class`, `Spell`, `Note`) VALUES (25, 10, 108127, 'Language of Pandaren Neutral');
REPLACE INTO `playercreateinfo_spell` (`race`, `class`, `Spell`, `Note`) VALUES (25, 10, 131701, 'Racials of pandarens');
REPLACE INTO `playercreateinfo_spell` (`race`, `class`, `Spell`, `Note`) VALUES (26, 1, 107072, 'Racials of pandarens');
REPLACE INTO `playercreateinfo_spell` (`race`, `class`, `Spell`, `Note`) VALUES (26, 1, 107073, 'Racials of pandarens');
REPLACE INTO `playercreateinfo_spell` (`race`, `class`, `Spell`, `Note`) VALUES (26, 1, 107074, 'Racials of pandarens');
REPLACE INTO `playercreateinfo_spell` (`race`, `class`, `Spell`, `Note`) VALUES (26, 1, 107076, 'Racials of pandarens');
REPLACE INTO `playercreateinfo_spell` (`race`, `class`, `Spell`, `Note`) VALUES (26, 1, 107079, 'Racials of pandarens');
REPLACE INTO `playercreateinfo_spell` (`race`, `class`, `Spell`, `Note`) VALUES (26, 1, 108127, 'Language of Pandaren Neutral');
REPLACE INTO `playercreateinfo_spell` (`race`, `class`, `Spell`, `Note`) VALUES (26, 1, 131701, 'Racials of pandarens');
REPLACE INTO `playercreateinfo_spell` (`race`, `class`, `Spell`, `Note`) VALUES (26, 3, 107072, 'Racials of pandarens');
REPLACE INTO `playercreateinfo_spell` (`race`, `class`, `Spell`, `Note`) VALUES (26, 3, 107073, 'Racials of pandarens');
REPLACE INTO `playercreateinfo_spell` (`race`, `class`, `Spell`, `Note`) VALUES (26, 3, 107074, 'Racials of pandarens');
REPLACE INTO `playercreateinfo_spell` (`race`, `class`, `Spell`, `Note`) VALUES (26, 3, 107076, 'Racials of pandarens');
REPLACE INTO `playercreateinfo_spell` (`race`, `class`, `Spell`, `Note`) VALUES (26, 3, 107079, 'Racials of pandarens');
REPLACE INTO `playercreateinfo_spell` (`race`, `class`, `Spell`, `Note`) VALUES (26, 3, 108127, 'Language of Pandaren Neutral');
REPLACE INTO `playercreateinfo_spell` (`race`, `class`, `Spell`, `Note`) VALUES (26, 3, 131701, 'Racials of pandarens');
REPLACE INTO `playercreateinfo_spell` (`race`, `class`, `Spell`, `Note`) VALUES (26, 4, 107072, 'Racials of pandarens');
REPLACE INTO `playercreateinfo_spell` (`race`, `class`, `Spell`, `Note`) VALUES (26, 4, 107073, 'Racials of pandarens');
REPLACE INTO `playercreateinfo_spell` (`race`, `class`, `Spell`, `Note`) VALUES (26, 4, 107074, 'Racials of pandarens');
REPLACE INTO `playercreateinfo_spell` (`race`, `class`, `Spell`, `Note`) VALUES (26, 4, 107076, 'Racials of pandarens');
REPLACE INTO `playercreateinfo_spell` (`race`, `class`, `Spell`, `Note`) VALUES (26, 4, 107079, 'Racials of pandarens');
REPLACE INTO `playercreateinfo_spell` (`race`, `class`, `Spell`, `Note`) VALUES (26, 4, 108127, 'Language of Pandaren Neutral');
REPLACE INTO `playercreateinfo_spell` (`race`, `class`, `Spell`, `Note`) VALUES (26, 4, 131701, 'Racials of pandarens');
REPLACE INTO `playercreateinfo_spell` (`race`, `class`, `Spell`, `Note`) VALUES (26, 5, 107072, 'Racials of pandarens');
REPLACE INTO `playercreateinfo_spell` (`race`, `class`, `Spell`, `Note`) VALUES (26, 5, 107073, 'Racials of pandarens');
REPLACE INTO `playercreateinfo_spell` (`race`, `class`, `Spell`, `Note`) VALUES (26, 5, 107074, 'Racials of pandarens');
REPLACE INTO `playercreateinfo_spell` (`race`, `class`, `Spell`, `Note`) VALUES (26, 5, 107076, 'Racials of pandarens');
REPLACE INTO `playercreateinfo_spell` (`race`, `class`, `Spell`, `Note`) VALUES (26, 5, 107079, 'Racials of pandarens');
REPLACE INTO `playercreateinfo_spell` (`race`, `class`, `Spell`, `Note`) VALUES (26, 5, 108127, 'Language of Pandaren Neutral');
REPLACE INTO `playercreateinfo_spell` (`race`, `class`, `Spell`, `Note`) VALUES (26, 5, 131701, 'Racials of pandarens');
REPLACE INTO `playercreateinfo_spell` (`race`, `class`, `Spell`, `Note`) VALUES (26, 7, 107072, 'Racials of pandarens');
REPLACE INTO `playercreateinfo_spell` (`race`, `class`, `Spell`, `Note`) VALUES (26, 7, 107073, 'Racials of pandarens');
REPLACE INTO `playercreateinfo_spell` (`race`, `class`, `Spell`, `Note`) VALUES (26, 7, 107074, 'Racials of pandarens');
REPLACE INTO `playercreateinfo_spell` (`race`, `class`, `Spell`, `Note`) VALUES (26, 7, 107076, 'Racials of pandarens');
REPLACE INTO `playercreateinfo_spell` (`race`, `class`, `Spell`, `Note`) VALUES (26, 7, 107079, 'Racials of pandarens');
REPLACE INTO `playercreateinfo_spell` (`race`, `class`, `Spell`, `Note`) VALUES (26, 7, 108127, 'Language of Pandaren Neutral');
REPLACE INTO `playercreateinfo_spell` (`race`, `class`, `Spell`, `Note`) VALUES (26, 7, 131701, 'Racials of pandarens');
REPLACE INTO `playercreateinfo_spell` (`race`, `class`, `Spell`, `Note`) VALUES (26, 8, 107072, 'Racials of pandarens');
REPLACE INTO `playercreateinfo_spell` (`race`, `class`, `Spell`, `Note`) VALUES (26, 8, 107073, 'Racials of pandarens');
REPLACE INTO `playercreateinfo_spell` (`race`, `class`, `Spell`, `Note`) VALUES (26, 8, 107074, 'Racials of pandarens');
REPLACE INTO `playercreateinfo_spell` (`race`, `class`, `Spell`, `Note`) VALUES (26, 8, 107076, 'Racials of pandarens');
REPLACE INTO `playercreateinfo_spell` (`race`, `class`, `Spell`, `Note`) VALUES (26, 8, 107079, 'Racials of pandarens');
REPLACE INTO `playercreateinfo_spell` (`race`, `class`, `Spell`, `Note`) VALUES (26, 8, 108127, 'Language of Pandaren Neutral');
REPLACE INTO `playercreateinfo_spell` (`race`, `class`, `Spell`, `Note`) VALUES (26, 8, 131701, 'Racials of pandarens');
REPLACE INTO `playercreateinfo_spell` (`race`, `class`, `Spell`, `Note`) VALUES (26, 10, 107072, 'Racials of pandarens');
REPLACE INTO `playercreateinfo_spell` (`race`, `class`, `Spell`, `Note`) VALUES (26, 10, 107073, 'Racials of pandarens');
REPLACE INTO `playercreateinfo_spell` (`race`, `class`, `Spell`, `Note`) VALUES (26, 10, 107074, 'Racials of pandarens');
REPLACE INTO `playercreateinfo_spell` (`race`, `class`, `Spell`, `Note`) VALUES (26, 10, 107076, 'Racials of pandarens');
REPLACE INTO `playercreateinfo_spell` (`race`, `class`, `Spell`, `Note`) VALUES (26, 10, 107079, 'Racials of pandarens');
REPLACE INTO `playercreateinfo_spell` (`race`, `class`, `Spell`, `Note`) VALUES (26, 10, 108127, 'Language of Pandaren Neutral');
REPLACE INTO `playercreateinfo_spell` (`race`, `class`, `Spell`, `Note`) VALUES (26, 10, 131701, 'Racials of pandarens');
