insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('1442','0','67231','0','L\'epreuve du roi');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('1509','0','61243','0','Gekkan');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('1510','0','61243','0','Gekkan');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('1441','0','61398','467','Xin le maitre d\'arme');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('1409','0','0','0','Protecteurs de l\'eternel //TODO ADD BUNNY');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('1505','0','62983','0','Lei shi');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('1431','0','60999','535','Sha de la peur');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('1422','0','59303','0','Maitre chien Braun');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('1421','0','58632','0','Maitre d\'armes Harlan');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('1420','0','59150','473','Tisseur de flammes Koegler');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('1423','0','59789','0','Thalnos le déchiqueteur d\'âmes');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('1424','0','59223','0','Frère Korloff');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('1425','0','3977','474','Grande inquisitrice Blanchetête');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('1426','0','58633','0','Instructrice Froidecoeur');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('1427','0','59184','0','Jandice Barov');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('1428','0','59153','0','Cliquettripes');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('1429','0','59200','0','Lilian Voss');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('1430','0','59080','472','Sombre Maitre Gandling');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('1395','0','60089','0','Le garde de pierre - bunny');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('1390','0','60009','0','Feng le maudit');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('1434','0','60143','531','Garaljal le lieur d\'esprit');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('1407','0','0','0','Volonté de l\'empereur //todo bunny');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('1507','0','62980','0','Vizir Imperial Zor\'lok');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('1504','0','62543','0','Seigneur des lames');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('1463','0','62164','0','Garalon');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('1498','0','62397','0','Seigneur du vent');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('1499','0','62511','0','Sculpte ambre');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('1501','0','62837','533','Grande impératrice');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('1465','0','61567','0','Vizir Jin’bak');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('1502','0','61634','0','Commandant Vo\'jak');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('1447','0','61485','0','General pa\'valak');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('1464','0','62205','0','Chef d\'escadre ner\'onok');
